title: Brindley
#kiosk_mode:
#    kiosk: true
views:
  - path: default_view
    title: Home
    icon: mdi:home-assistant
    cards:
      - type: custom:layout-card
        layout_type: custom:masonry-layout
        layout:
          max_cols: 1
          width: 1200
        cards:
          - type: horizontal-stack
            cards:
              - type: calendar
                entities:
                  - calendar.paul_and_ash
                initial_view: listWeek
              - type: vertical-stack
                cards:
                  - type: horizontal-stack
                    cards:
                      - type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - person.paul
                          - type: entities
                            entities:
                              - person.ashley
                      - type: button
                        tap_action:
                          action: toggle
                        entity: input_boolean.has_hazel_been_fed
                        name: Hazel Fed?
                        show_state: false
                  - type: horizontal-stack
                    cards:
                      - type: light
                        entity: light.ashleys_bedside_lamp
                      - type: light
                        entity: light.living_room_lamp
                  - type: horizontal-stack
                    cards:
                      - type: vertical-stack
                        cards:
                          - type: button
                            tap_action:
                              action: toggle
                            entity: switch.baby_yoda
                          - type: button
                            tap_action:
                              action: toggle
                            entity: switch.family_room_light
                      - type: vertical-stack
                        cards:
                          - type: button
                            tap_action:
                              action: toggle
                            entity: switch.wax_lamp
                          - type: button
                            tap_action:
                              action: toggle
                            entity: switch.guest_room
                      - type: vertical-stack
                        cards:
                          - type: button
                            tap_action:
                              action: toggle
                            entity: switch.mantle
              - type: vertical-stack
                cards:
                  - type: weather-forecast
                    entity: weather.brindley
                    show_forecast: true
                  - type: custom:mini-media-player
                    entity: media_player.spotify_home
                    artwork: cover
                    source: full
                    hide:
                      controls: false
                      power: true
                      runtime: true
                      shuffle: false
                      volume: false
                    icon: mdi:spotify
                    info: scroll
                    name: Spotify
                    shortcuts:
                      buttons:
                        - id: 'spotify:user:spotify:playlist:37i9dQZF1E385Lpa6pU5O1'
                          name: Daily Mix 1
                          type: playlist
                        - id: 'spotify:user:wzwick:playlist:37i9dQZF1E3a80AcTsIVUl'
                          name: Daily Mix 2
                          type: playlist
                        - artwork: cover
                          id: 'spotify:user:spotify:playlist:37i9dQZF1DX0b1hHYQtJjp'
                          name: Just Good Music
                          type: playlist
                        - id: 'spotify:user:spotify:playlist:37i9dQZF1DZ06evO25lU76'
                          name: Quinn XCII
                          type: playlist
                        - id: 'spotify:user:spotify:playlist:37i9dQZF1DXdsy92d7BLpC'
                          name: Weekend Vibes
                          type: playlist
                        - id: 'spotify:user:spotify:playlist:37i9dQZF1DWU13kKnk03AP'
                          name: Daily Lift
                          type: playlist
                      columns: 2
  - path: spotify
    title: Spotify
    icon: mdi:spotify
    cards:
      - type: custom:layout-card
        layout_type: custom:masonry-layout
        layout:
          max_cols: 1
          width: 1200
        cards:
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: 'custom:button-card'
                    entity: sensor.daily_mix_1
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
                  - type: 'custom:button-card'
                    entity: sensor.daily_mix_2
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
                  - type: 'custom:button-card'
                    entity: sensor.daily_mix_3
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
                  - type: 'custom:button-card'
                    entity: sensor.playlist_1
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
                  - type: 'custom:button-card'
                    entity: sensor.playlist_2
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
              - type: horizontal-stack
                cards:
                  - type: 'custom:button-card'
                    entity: sensor.daily_mix_4
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
                  - type: 'custom:button-card'
                    entity: sensor.daily_mix_5
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
                  - type: 'custom:button-card'
                    entity: sensor.daily_mix_6
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
                  - type: 'custom:button-card'
                    entity: sensor.playlist_3
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
                  - type: 'custom:button-card'
                    entity: sensor.playlist_4
                    show_entity_picture: true
                    show_label: false
                    size: 70%
                    styles:
                      card:
                        - height: 200px
                        - background-color: rgba(0, 0, 0, 0.0)
                        - box-shadow: 'none'
                      label:
                        - font-size: 14px
                      name:
                        - font-size: 14px
                    name: |
                      [[[ return entity.attributes.name; ]]]
                    label: |
                      [[[ return entity.attributes.label; ]]]
                    entity_picture: |
                      [[[ return entity.attributes.image; ]]]
                    tap_action:
                      action: call-service
                      service: spotcast.start
                      service_data:
                        spotify_device_id: 'cab05a58-4316-4ac3-826a-24fdcc4ca416'
                        uri: |
                          [[[ return entity.attributes.url; ]]]
              - type: horizontal-stack
                cards:
                  - type: 'custom:mini-media-player'
                    entity: media_player.spotify_home
                    name: Spotify Player
                    icon: mdi:spotify
                    artwork: cover
                    source: full
                    hide:
                      power: true
                      progress: true
                      controls: false
                      runtime: true
                      shuffle: false
                      volume: false
                    info: scroll
  - path: power
    title: Homelab Power Usage
    icon: mdi:flash
    panel: true
    badges: []
    cards:
      - type: iframe
        url: >-
          https://grafana.pkh.icu/d/Xngf_ABGk/ipad-nut-ups-dashboard?orgId=1&refresh=1h
        aspect_ratio: 50%
  - path: map
    title: Map
    icon: mdi:map-marker-radius
    badges: []
    cards:
      - type: map
        entities:
          - entity: device_tracker.paul_s_iphone
        default_zoom: 12
        title: PAUL
        hours_to_show: 6
      - type: map
        entities:
          - entity: device_tracker.iphone
        title: ASHLEY
        default_zoom: 12
        hours_to_show: 6
  - path: nas
    title: NAS
    icon: mdi:nas
    badges: []
    cards:
      - type: glance
        entities:
          - entity: binary_sensor.jeditemple_drive_1_below_min_remaining_life
          - entity: binary_sensor.jeditemple_drive_1_exceeded_max_bad_sectors
          - entity: binary_sensor.jeditemple_drive_2_below_min_remaining_life
          - entity: binary_sensor.jeditemple_drive_2_exceeded_max_bad_sectors
          - entity: binary_sensor.jeditemple_drive_3_below_min_remaining_life
          - entity: binary_sensor.jeditemple_drive_3_exceeded_max_bad_sectors
          - entity: binary_sensor.jeditemple_drive_4_below_min_remaining_life
          - entity: binary_sensor.jeditemple_drive_4_exceeded_max_bad_sectors
        columns: 2
        state_color: true
        title: Synology Drive Status
      - type: sensor
        entity: sensor.jeditemple_cpu_load_5_min
        graph: line
      - type: sensor
        entity: sensor.jeditemple_cpu_load_15_min
        graph: line
      - type: sensor
        entity: sensor.jeditemple_cpu_load_total
        graph: line
      - type: entity
        entity: binary_sensor.jeditemple_update_available
      - type: entity
        entity: binary_sensor.jeditemple_security_status
      - type: entities
        entities:
          - entity: sensor.tripplite_1500_status
          - entity: sensor.tripplite_1500_load
          - entity: sensor.tripplite1_battery_charge
          - entity: sensor.tripplite_1500_battery_runtime
        title: Basement
      - type: entity
        entity: binary_sensor.updater
        title: Home Assistant Update
  - path: plex
    title: TESTING
    badges: []
    cards:
      - type: entity
        entity: sensor.tautulli_media_type
      - type: entity
        entity: sensor.tautulli_playing
      - type: button
        tap_action:
          action: toggle
        entity: media_player.home_theater
        show_state: true
      - type: entity
        entity: sensor.firehd10_battery
